/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "register": [],
    "register.store": [],
    "login": [],
    "login.store": [],
    "logout.store": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.notice": [],
    "verification.send": [],
    "dashboard": [],
    "budgets.create": [],
    "budgets.store": [],
    "budgets.show": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.edit": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.update": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.destroy": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.store": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.update": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        },
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "expenses.destroy": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        },
        {
            "name": "expense",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
